// reactapp/Tabs.tsx
import * as React from 'react';

interface TabProps {
    title: string;
    content: JSX.Element;
    isActive?: boolean;
    hotKey?: string;
}

export class Tab extends React.Component<TabProps, any> {
    constructor() {
        super();
    }
    public render() {
        return <div>{this.props.content}</div>;
    }
}

function SetActiveTab(tabs: Tab[], index: number) {
    tabs.forEach((t, i) => {
        t.props.isActive = i == index;
    });
}

export class Tabs extends React.Component<{children?: any}, {activeTabIndex?: number}> {
    constructor() {
        super();
        this.state = {};
    }

    private tabHeaders?: Element;

    public render() {
        let activeTabIndex = this.state.activeTabIndex || 0;
        let tabs = this.props.children || [] as Tab[];
        return (
            <div className='nav-tabs'>
            <ul className='nav-tabs' tabIndex={0} onKeyDown={ e => this.keyDown(e) } ref={t => { this.tabHeaders = t; }}>
                {tabs.map((tab: Tab, index: number) => (
                    <li className={index == activeTabIndex ? "active" : ""} key={index} onClick={() => this.setActiveTab(index)}>{this.getTabHeader(tab.props.title, tab.props.hotKey)}</li>
                ))}
                </ul>
                <div className='nav-tab-content'>
                    {tabs[activeTabIndex].props.content }
                </div>
            </div>
    )};

    public componentDidMount() {
        document.addEventListener('keydown', e => this.globalKeyDown(e));
    }

    public componentWillUnmount() {        
        document.removeEventListener('keydown', e => this.globalKeyDown(e as any));
    }

    getTabHeader(title: string, hotKey?: string): JSX.Element {
        var index: number;
        if (hotKey) {
            if ((index = title.toLowerCase().indexOf(hotKey.toLowerCase())) >= 0) {
                return <span>{title.substring(0, index)}<u>{title.substring(index, index + 1)}</u>{title.substring(index + 1)}</span>;
            } else {
                return <span>{title}&nbsp;(<u>{hotKey.toUpperCase()}</u>)</span>;
            }
        }
        return <span>{title}</span>;
    }

    setActiveTab(index: number) {
        this.setState({ activeTabIndex: index });
    }

    keyDown(event: React.KeyboardEvent<HTMLUListElement>) {
        if (event.keyCode == 38 || event.keyCode == 37) {
            if (this.state.activeTabIndex > 0) {
                this.setActiveTab(this.state.activeTabIndex - 1);
            }
            event.preventDefault();
        } else if (event.keyCode == 40 || event.keyCode == 39) {
            if (this.state.activeTabIndex < this.props.children.length - 1) {
                this.setActiveTab(this.state.activeTabIndex + 1);
            }
            event.preventDefault();
        }
    }

    globalKeyDown(event: KeyboardEvent) {
        var index: number;
        if (event.altKey && event.shiftKey) {
            if ((index = (this.props.children as Tab[] || [] as Tab[]).findIndex(t => event.key.localeCompare(t.props.hotKey, undefined, { sensitivity: 'accent' }) == 0)) >= 0) {
                this.setActiveTab(index);
                this.tabHeaders && (this.tabHeaders as any).focus();
                event.preventDefault();
            }
        }
    }
}

// ngapp/tabs.component.ts
import { Component, Input, ContentChildren, QueryList, ViewChild, ElementRef, AfterContentInit, HostListener } from '@angular/core';

import { TabComponent } from './tab.component';

@Component({
    moduleId: module.id,
    selector: 'ng-tabs',
    template: `
        <ul #tabHeader class="nav-tabs" (keydown)=handleKeyPress($event) tabindex="0">
            <li *ngFor="let tab of tabs; let i = index" (click)=selectTab(i) [class.active]="isActiveTab(i)"
                [innerHTML]="getTabHeader(tab.title, tab.hotKey)">
            </li>
        </ul>
        <div class="nav-tab-content">
            <ng-content></ng-content>
        </div>
        `
})
export class TabsComponent implements AfterContentInit {
    @Input("activeTab")
    activeTabIndex: number;

    @ContentChildren(TabComponent)
    tabs: QueryList<TabComponent>;

    @ViewChild('tabHeader')
    private tabHeader: ElementRef; 

    constructor() {
        this.activeTabIndex = 0;
    }

    get activeTab(): TabComponent {
        return this.tabs.toArray()[this.activeTabIndex];
    }

    getTabHeader(title: string, hotKey?: string): string {
        var index: number;
        if (hotKey) {
            if ((index = title.toLowerCase().indexOf(hotKey.toLowerCase())) >= 0) {
                return title.substring(0, index) + '<u>' + title.substring(index, index + 1) + '</u>' + title.substring(index + 1);
            } else {
                return title + '&nbsp;(<u>' + hotKey.toUpperCase() + '</u>)';
            }
        }
        return title;
    }

    ngAfterContentInit() {
        if (this.activeTabIndex >= this.tabs.length) {
            this.activeTabIndex = 0;
        }
        this.selectTab(this.activeTabIndex);
    }

    isActiveTab(index: number) {
        return index == this.activeTabIndex;
    }

    selectTab(index: number, focusActiveTab?: boolean) {
        this.activeTabIndex = index;
        this.tabs.forEach((tab, index) => {
            tab.isActive = index == this.activeTabIndex;
        });
    }

    handleKeyPress(event: KeyboardEvent) {
        if (event.keyCode == 38 || event.keyCode == 37) {
            if (this.activeTabIndex > 0) {
                this.selectTab(this.activeTabIndex - 1);
            }
            event.preventDefault();
        } else if (event.keyCode == 40 || event.keyCode == 39) {
            if (this.activeTabIndex < this.tabs.length - 1) {
                this.selectTab(this.activeTabIndex + 1);
            }
            event.preventDefault();
        }
    }

    @HostListener('document:keydown', ['$event'])
    windowKeyDown(event: KeyboardEvent) {
        var index: number;
        if (event.altKey && !event.shiftKey
            && (index = this.tabs.toArray().findIndex(t => event.key.localeCompare(t.hotKey, undefined, { sensitivity: 'accent' }) == 0)) >= 0) {
            this.selectTab(index);
            this.tabHeader.nativeElement.focus();
            event.preventDefault();
        }
    }
}
